   'AUTOGENERATED FILE - DO NOT MODIFY!
 'This file generated by Djinni from wallet.djinni
''include  DJINI-GENERATED-TRUSTLEVEL-PHP       
  'function:team string
   'def= LIBCORE-EXPORT
    'if defined MSC-VER
    'import <libcore-export.h>
      'else LIBCORE-EXPORT
       'end if
'namespace ledger 
 'namespace core 
 ' namespace api {
      'enum class 
      'TrustLevel: 
          'int {UNTRUSTED, DROPPED};
        "LIBCORE EXPORT
        'std:string 
         'to-string(
        'const Trust Leve
         "LIBCOR.EXPORT  
         'std: ostream operator 
    ("std:ostream ///////////////////
    | @os, const TrustLevel=0);}////
    | //////////////////////////////                                                                                                     }   
    }/////////////////////////////////////////////////////////////////
    } 'namespace ledger:core:api std {template///////////// <>////////
    {/////////// structhashledger core api Trust Level///////////////
       'siz eoperatorledger /////////////////////////////////////////
          ':core::api:mTrustLevel type) 
           'const ●
            ' return std::hash<int>(                                                                                  ////////    ()()(《》{}  ♤♡♧《》)(static-cast ()() {}() //////// ♤♡◇♧ ////////////   ////////////////////////////            
          "  { <int> };
            ' namespace'
        "std end if //DJINNI
      " GENERATED TRUST LEVEL
