name: core-prebuild
on:
  push:
    tags:
      - '*'
jobs:
  prebuild-for-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - uses: actions/setup-python@v1
        with:
          python-version: '2.7.x'
      - name: install
        run: yarn --frozen-lockfile --ignore-scripts
      - name: fetch libcore
        run: yarn preinstall
      - name: config yarn
        if: runner.os == 'Windows'
        run: yarn config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
      - name: prebuild for electron 7
        run: npx node-pre-gyp configure build package --runtime=electron --target=7.1.9 --build-from-source --dist-url=https://electronjs.org/headers
      - name: prebuild for electron 8
        run: npx node-pre-gyp configure build package --runtime=electron --target=8.0.0 --build-from-source --dist-url=https://electronjs.org/headers
      - name: prebuild for node 12
        run: npx node-pre-gyp configure build package --target=12.16.0
      - name: prebuild for node 13
        run: npx node-pre-gyp configure build package --target=13.8.0
      - name: publish
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx node-pre-gyp-github publish
